Repository AY1920S1-CS2103-T16-4/main, pull requests merged in 2019-10, with the labels that each got.

#72 WIP: Add AutoExpense
  .gitignore
  .hooks/pre-push
  initHooks.sh
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/AutoExpense.java
  src/main/java/seedu/address/model/person/AutoExpenseList.java
  src/main/java/seedu/address/model/person/Expense.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: feature.DataOrganization

#113 Update DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
Labels: PR:approved-can-merge

#123 Update gitignore to exclude bin and misc files
  .gitignore
Labels: PR:ready-for-review

#121 Update DG on UI component section
  docs/DeveloperGuide.adoc
Labels: PR:ready-for-review

#141 New UI feature to change font in application
  src/main/java/seedu/address/logic/commands/ChangeFontCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCategoryCommand.java
  src/main/java/seedu/address/logic/commands/ListFontCommand.java
  src/main/java/seedu/address/logic/commands/TogglePanelCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ChangeFontCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TogglePanelCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/CategoryList.java
  src/main/java/seedu/address/model/person/PanelName.java
  src/main/java/seedu/address/model/statistics/DailyList.java
  src/main/java/seedu/address/ui/EntryListPanel.java
  src/main/java/seedu/address/ui/FontManager.java
  src/main/java/seedu/address/ui/FontName.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: PR:ready-for-review

#137 Fix some existing tests and Add tests for AutoExpense
  build.gradle
  src/main/java/seedu/address/logic/commands/AddAutoExpenseCommand.java
  src/main/java/seedu/address/logic/parser/AddAutoExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/AutoExpense.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/util/Frequency.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/AutoExpenseTest.java
  src/test/java/seedu/address/testutil/AutoExpenseBuilder.java
  src/test/java/seedu/address/testutil/EditEntryDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalAutoExpenses.java
  src/test/java/seedu/address/testutil/TypicalEntries.java
Labels: PR:ready-for-review

#143 Edit Architecture DevGuide
  docs/DeveloperGuide.adoc
Labels: PR:ready-for-review

#144 Edit User Guide, Developer Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ToggleActivityDiagram.puml
  docs/diagrams/ToggleSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ToggleActivityDiagram.png
  docs/images/ToggleSequenceDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/ui/BudgetCard.java
  src/main/java/seedu/address/ui/FontManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderPanel.java
  src/main/java/seedu/address/ui/WishCard.java
  src/main/java/seedu/address/ui/WishListCard.java
  src/main/java/seedu/address/ui/WishListPanel.java
  src/main/resources/WishListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: PR:ready-for-review

#145 Autoexp edit
  src/main/java/seedu/address/logic/commands/AddAutoExpenseCommand.java
  src/main/java/seedu/address/logic/commands/EditAutoExpenseCommand.java
  src/main/java/seedu/address/logic/parser/AddAutoExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditAutoExpenseCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: PR:ready-for-review

#154 Add DeleteAutoExpense
  src/main/java/seedu/address/logic/commands/DeleteAutoExpenseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAutoExpenseCommandParser.java
Labels: PR:ready-for-review

#155 Implementing intermediate Statistics
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditBudgetCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditExpenseCommand.java
  src/main/java/seedu/address/logic/commands/EditWishCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/StatisticsCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/SwitchStatisticsCommand.java
  src/main/java/seedu/address/logic/commands/TogglePanelCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StatisticsCommandParser.java
  src/main/java/seedu/address/logic/parser/SwitchCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Category.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/SortType.java
  src/main/java/seedu/address/model/person/predicates/AmountContainsValuePredicate.java
  src/main/java/seedu/address/model/person/predicates/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/entries/CategoryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/statistics/CategoryStatistics.java
  src/main/java/seedu/address/model/statistics/EntryContainsCategoryPredicate.java
  src/main/java/seedu/address/model/statistics/EntryContainsDayPredicate.java
  src/main/java/seedu/address/model/statistics/EntryTimeContainsPredicate.java
  src/main/java/seedu/address/model/statistics/MonthList.java
  src/main/java/seedu/address/model/statistics/Statistics.java
  src/main/java/seedu/address/model/statistics/StatisticsManager.java
  src/main/java/seedu/address/model/util/EntryComparator.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsGraphics.java
  src/main/java/seedu/address/ui/StatisticsPieChart.java
  src/main/java/seedu/address/ui/StatisticsTable.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
  src/main/resources/view/ChartTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Statistics.fxml
  src/main/resources/view/StatisticsChart.fxml
  src/main/resources/view/StatisticsPieChart.fxml
  src/main/resources/view/StatisticsTable.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: feature.DataPresentation

#175 Enable startup expense generation by autoexpenses
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/AutoExpense.java
  src/main/java/seedu/address/model/person/Date.java
Labels: PR:ready-for-review
