Repository AY1920S1-CS2103-T16-4/main, pull requests merged in 2019-11, with the labels that each got.

#187 Edit UserGuide for Mock PE
  docs/UserGuide.adoc
Labels: PR:ready-for-review

#188 Edit Budget, Undo/ Redo
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddBudgetCommand.java
  src/main/java/seedu/address/logic/commands/EditBudgetCommand.java
  src/main/java/seedu/address/logic/commands/remindercommands/AddReminderCommand.java
  src/main/java/seedu/address/logic/parser/EditBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/remindercommandparsers/SetEntryReminderCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Budget.java
  src/main/java/seedu/address/model/person/BudgetList.java
  src/main/java/seedu/address/model/person/ExpenseList.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
Labels: PR:ready-for-review

#186 Implementing periods for viewStatistics.
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/BudgetListCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditBudgetCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditWishCommand.java
  src/main/java/seedu/address/logic/commands/FindBudgetCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindWishCommand.java
  src/main/java/seedu/address/logic/commands/StatisticsCommand.java
  src/main/java/seedu/address/logic/commands/WishListCommand.java
  src/main/java/seedu/address/logic/parser/FindBudgetCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindWishCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StatisticsCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Amount.java
  src/main/java/seedu/address/model/person/Budget.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/predicates/EntryContainsAmountPredicate.java
  src/main/java/seedu/address/model/person/predicates/EntryContainsCategoryPredicate.java
  src/main/java/seedu/address/model/person/predicates/EntryContainsDescriptionPredicate.java
  src/main/java/seedu/address/model/person/predicates/EntryContainsTagsPredicate.java
  src/main/java/seedu/address/model/person/predicates/budget/BudgetContainsDatePredicate.java
  src/main/java/seedu/address/model/reminders/conditions/EntrySpecificCondition.java
  src/main/java/seedu/address/model/statistics/StatisticsManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAutoExpense.java
  src/main/java/seedu/address/storage/JsonAdaptedBudget.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/JsonAdaptedIncome.java
  src/main/java/seedu/address/storage/JsonAdaptedWish.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/ReminderConditionMapper.java
  src/main/java/seedu/address/ui/ExpenseCard.java
  src/main/java/seedu/address/ui/IncomeCard.java
  src/main/resources/view/ExpenseCard.fxml
  src/main/resources/view/IncomeCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AutoExpenseBuilder.java
  src/test/java/seedu/address/testutil/EditEntryDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EntryBuilder.java
  src/test/java/seedu/address/testutil/TypicalEntries.java
Labels: PR:needs-rebase, PR:tests-failing

#251 Work on UI
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/ChangeFontCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/SetDarkThemeCommand.java
  src/main/java/seedu/address/logic/commands/SetLightThemeCommand.java
  src/main/java/seedu/address/logic/parser/GuiltTripParser.java
  src/main/java/seedu/address/model/GuiltTrip.java
  src/main/java/seedu/address/storage/JsonSerializableGuiltTrip.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/util/Theme.java
  src/main/resources/view/ConditionListCard.fxml
  src/main/resources/view/ExpenseCard.fxml
  src/main/resources/view/IncomeCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderListCard.fxml
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: PR:ready-for-review

#253 Shorten prefixes
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SetDarkThemeCommand.java
  src/main/java/seedu/address/logic/commands/SetLightThemeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/GuiltTrip.java
  src/main/resources/view/ExpenseCard.fxml
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: PR:ready-for-review

#242 Edit Budget
  src/main/java/seedu/address/commons/core/step/Step.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditBudgetCommand.java
  src/main/java/seedu/address/logic/commands/ListBudgetCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/GuiltTripParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedGuiltTrip.java
  src/main/java/seedu/address/model/entry/Budget.java
  src/main/java/seedu/address/model/entry/BudgetAmount.java
  src/main/java/seedu/address/model/entry/ExpenseMatchesBudgetPredicate.java
  src/main/java/seedu/address/model/entry/IncomeMatchesBudgetPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: PR:ready-for-review

#241 Enable informative Error Messages
  src/main/java/seedu/guilttrip/commons/core/Messages.java
  src/main/java/seedu/guilttrip/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/guilttrip/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/guilttrip/logic/parser/CliSyntax.java
  src/main/java/seedu/guilttrip/logic/parser/ParserUtil.java
  src/main/java/seedu/guilttrip/logic/parser/Prefix.java
  src/main/java/seedu/guilttrip/logic/parser/addcommandparsers/AddAutoExpenseCommandParser.java
  src/main/java/seedu/guilttrip/model/util/Frequency.java
Labels: PR:ready-for-review

#265 Force findWish to take in prefixed args
  docs/UserGuide.adoc
Labels: PR:ready-for-review

#264 Fix typo on "ANUALLY"
  src/main/java/seedu/guilttrip/model/util/Frequency.java
Labels: PR:ready-for-review

#273 Hack hack hack
  src/main/java/seedu/guilttrip/commons/core/Version.java
  src/main/java/seedu/guilttrip/logic/LogicManager.java
  src/main/java/seedu/guilttrip/logic/commands/GuiltTripCommandSuggester.java
  src/main/java/seedu/guilttrip/logic/commands/addcommands/AddAutoExpenseCommand.java
  src/main/java/seedu/guilttrip/logic/parser/remindercommandparsers/EditReminderCommandParser.java
  src/main/java/seedu/guilttrip/model/Model.java
  src/main/java/seedu/guilttrip/model/ModelManager.java
  src/main/java/seedu/guilttrip/model/entry/AutoExpense.java
  src/main/java/seedu/guilttrip/model/entry/Budget.java
  src/main/java/seedu/guilttrip/model/entry/Entry.java
  src/main/java/seedu/guilttrip/model/entry/Expense.java
  src/main/java/seedu/guilttrip/model/entry/Wish.java
  src/main/java/seedu/guilttrip/model/reminders/Reminder.java
  src/main/java/seedu/guilttrip/model/reminders/conditions/Condition.java
  src/test/java/seedu/guilttrip/model/ModelStub.java
Labels: PR:ready-for-review

#284 Qol fixes
  src/main/java/seedu/guilttrip/logic/commands/GuiltTripCommandSuggester.java
  src/main/java/seedu/guilttrip/logic/parser/addcommandparsers/AddBudgetCommandParser.java
  src/main/java/seedu/guilttrip/logic/parser/addcommandparsers/AddCategoryCommandParser.java
  src/main/java/seedu/guilttrip/logic/parser/addcommandparsers/AddExpenseCommandParser.java
  src/main/java/seedu/guilttrip/logic/parser/addcommandparsers/AddIncomeCommandParser.java
  src/main/java/seedu/guilttrip/logic/parser/addcommandparsers/AddWishCommandParser.java
  src/main/java/seedu/guilttrip/model/entry/Date.java
  src/test/java/seedu/guilttrip/logic/parser/AddCategoryCommandParserTest.java
  src/test/java/seedu/guilttrip/logic/parser/AddExpenseCommandParserTest.java
  src/test/java/seedu/guilttrip/logic/parser/CommandParserTestUtil.java
Labels: PR:WIP

#289 Minor bug fixes
  src/main/java/seedu/guilttrip/commons/util/AutoExpenseUpdater.java
  src/main/java/seedu/guilttrip/logic/parser/addcommandparsers/AddExpenseCommandParser.java
  src/main/java/seedu/guilttrip/model/ModelManager.java
  src/main/java/seedu/guilttrip/model/entry/AutoExpense.java
Labels: PR:ready-for-review

#296 UserGuidie: AutoSuggest and AutoExpense
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/autoexpense_add.png
  docs/images/autoexpense_delete.png
  docs/images/autoexpense_edit.png
  docs/images/autosuggest_addExpense.png
  docs/images/autosuggest_hlp.png
  docs/images/autosuggest_startup.png
Labels: PR:ready-for-review

#294 Update UI class diagram, UI section in DG, add PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ChangeFontActivityDiagram.puml
  docs/diagrams/ChangeFontSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PartialUiClassDiagramForToggle.puml
  docs/diagrams/SetLightThemeActivityDiagram.puml
  docs/diagrams/SetLightThemeSequenceDiagram.puml
  docs/diagrams/ToggleActivityDiagram.puml
  docs/diagrams/ToggleSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ChangeFontActivityDiagram.png
  docs/images/ChangeFontSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PartialUiClassDiagramForToggle.png
  docs/images/SetLightThemeActivityDiagram.png
  docs/images/SetLightThemeSequenceDiagram.png
  docs/images/ToggleActivityDiagram.png
  docs/images/ToggleSequenceDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/team/jessicax941.adoc
  src/main/java/seedu/guilttrip/commons/core/GuiSettings.java
  src/main/java/seedu/guilttrip/logic/commands/CommandResult.java
  src/main/java/seedu/guilttrip/logic/commands/uicommands/ChangeFontCommand.java
  src/main/java/seedu/guilttrip/model/entry/BudgetStub.java
  src/main/java/seedu/guilttrip/model/entry/Person.java
  src/main/java/seedu/guilttrip/ui/MainWindow.java
  src/main/java/seedu/guilttrip/ui/util/FontManager.java
  src/main/java/seedu/guilttrip/ui/util/Theme.java
  src/main/java/seedu/guilttrip/ui/wishlist/WishListCard.java
  src/test/java/seedu/guilttrip/storage/StorageManagerTest.java
Labels: PR:ready-for-review

#181 Add DeveloperGuide for AutoExpense and AutoSuggest
  docs/DeveloperGuide.adoc
  docs/diagrams/AutoExpenseActivityDiagram.puml
  docs/diagrams/AutoExpenseSequenceDiagram.puml
  docs/diagrams/AutoSuggestClassDiagram.puml
  docs/images/AutoExpenseActivityDiagram.png
  docs/images/AutoExpenseSequenceDiagram.png
  docs/images/AutoSuggestClassDiagram.png
  src/main/java/seedu/guilttrip/logic/commands/GuiltTripCommandSuggester.java
Labels: PR:approved-can-merge

#299 SwampertX PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/swampertx.adoc
Labels: PR:ready-for-review

#309 Edit PPP
  docs/team/rongrongrr.adoc
Labels: PR:approved-can-merge

#304 Some Docs Cosmetic Fixes
  README.adoc
  build.gradle
  docs/UserGuide.adoc
  docs/team/swampertx.adoc
  docs/templates/_header.html.slim
Labels: PR:ready-for-review
